library(nflfastR)
library(tidyverse)
library(ggimage)
data <- readRDS(url('https://raw.githubusercontent.com/guga31bb/nflfastR-data/master/data/play_by_play_2020.rds'))

sad <- data %>% filter(air_yards < -40) %>% summarize(posteam, defteam, receiver_player_name, yards_gained, qtr, quarter_seconds_remaining, posteam_score, defteam_score, ydstogo, down, drive, yrdln, yards_gained, pass_location, air_yards)
fdata <- data %>% filter(play_type == "pass") 
fdata <- fdata %>% group_by(air_yards) # %>% summarize(yards_gained, receiver_player_name)
View(sad)
Sys.sleep(1000)
print(sad)
fdata <<- fdata %>% summarize(air_yards, epa, complete_pass) 
ggplot(fdata, aes(x=air_yards, y=epa, colour=complete_pass)) + geom_point()
ggsave('airyards-epa.png', dpi=1000)
